Update to support new ddc apis
statiolake/ddc-ale pull request #7
Opened 2021-11-29 08:25 UTC by amadeus

Another day, another API change.

`refresh_candidates` was deprecated and deleted, which relegated this plugin to being completely broken. I've updated it to support the new callback api.  I'd like to give it a day or two to test, just to ensure nothing subtle is broken, but yeah, it does simply things a bunch.

2021-11-29 12:28 UTC, statiolake requested changes
Thanks for the update! It seems fine except the point I commented.

Is this change means that ddc.vim no longer blocks initial completion popup even if an asynchronous responses takes a long time or even never returns? If I understand correctly, now the implementation awaits for a heavy response again.

The reason you introduced `refresh_candidate()` was to speed up initial completion (provided by other sources) by returning empty result temporaly. Now what's the difference between this and my old implementation?

Note: it's just for curiosity (and to check my understanding) - I'm not saying I want to use old implementation again. Your implementation follows the example provided by Shougo, so I think this is more reliable solution.

2021-11-29 12:28 UTC, statiolake commented on autoload/ddc/ale.vim
> +    call s:callback(a:id, [])
The argument order seems opposite, i.e. it should be `s:callback(a:id, [])`. You can fix here, but it might be better to adjust the order of parameters to match with `ddc#calback()`'s.

2021-11-29 19:36 UTC, amadeus commented on autoload/ddc/ale.vim
> +    call s:callback(a:id, [])
I originally had this lol, but something was broken at the time, I ended up swapping them, then never swapped back, but yeah, should be fixed now

2021-11-29 19:39 UTC, amadeus commented
>>> The reason you introduced refresh_candidate() was to speed up initial completion (provided by other sources) by returning empty result temporaly. Now what's the difference between this and my old implementation?

Yeah, not sure about this now, perhaps ddc works around it? Or perhaps there's some modifications we can make to support this faster response functionality, @Shougo thoughts?

2021-11-30 01:17 UTC, Shougo commented
@amadeus @statiolake Please see it why I have changed the behavior.

https://github.com/Shougo/ddc.vim/pull/62

2021-12-01 00:23 UTC, amadeus commented
Alright, I've been sitting on this now for a day or two, seems to be working just fine, and feedback should be fully addressed!

2021-12-03 11:06 UTC, statiolake approved these changes
Thanks!

2021-12-03 11:06 UTC, merged